export type CategoryIcons =
  | 'soap'
  | 'teddy-bear'
  | 'snack'
  | 'snowflake'
  | 'salad'
  | 'paw'
  | 'meat'
  | 'fish'
  | 'cream'
  | 'coffee-beans'
  | 'coctail'
  | 'cigarette'
  | 'cheese'
  | 'car'
  | 'candy'
  | 'can-food'
  | 'broom'
  | 'bread'
  | 'water-bottle'
  | 'bottle'
  | 'apple'
  | 'wheat'

export type FineOneWhereType = string | number
